### 线性回归框架实现

1. 构造数据
2. 定义模型
3. 初始化变量
4. 定义优化函数
5. 定义损失函数
6. 训练
7. 检测训练效果

In [23]:
import torch
import matplotlib.pyplot as plt
import torch.nn as nn

In [24]:
def net(x, w, b):
    return torch.matmul(x, w) + b + torch.normal(0, 0.01, (1, 1))

In [25]:
true_w = torch.tensor([2., -3.4])
true_b = 4.2
data_size = 1000

true_x = torch.normal(0, 1, (data_size, 2))
true_y = net(true_x, true_w, true_b)
true_y = true_y.reshape(-1, 1)
# fig, ax = plt.subplots()
# ax.scatter(true_x[:, 0], true_y, s=1)
# plt.show()

data_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(true_x, true_y), batch_size=10)


In [26]:
w = nn.parameter.Parameter(torch.normal(0, .01, (1, 2)))
b = nn.parameter.Parameter(torch.zeros(1))
model = nn.Sequential(nn.Linear(2, 1))
# model[0].weight.data.normal_(0, 0.01)
# model[0].bias.data.fill_(0)
model[0].weight = w
model[0].bais = b
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.03)

In [27]:
epochs = 3
for epoch in range(epochs):
    for x, y in data_loader:
        optimizer.zero_grad()
        l = loss(model(x), y)
        l.backward()
        optimizer.step()
    with torch.no_grad():
        l = loss(model(true_x), true_y)
        print('epoch', epoch, 'loss', l)
        print(model[0].weight.detach().numpy(), model[0].bias.detach().numpy())

epoch 0 loss tensor(8.6076e-05)
[[ 1.9955729 -3.3979838]] [4.210695]
epoch 1 loss tensor(4.2323e-10)
[[ 1.9999878 -3.4000037]] [4.218533]
epoch 2 loss tensor(8.9221e-12)
[[ 1.9999999 -3.4000003]] [4.218547]
